In [6]:
import numpy as np

A = np.array([[18, 9, 13], [50, 23, 35], [-65, -31, -46]])
B = np.array([5, -5, 5])
T = np.array([[-4, -2, -3], [15, 7, 10], [-5, -2, -3]])

# inverse of the T
T_inv = np.linalg.inv(T)

# A = A * T_inv
A_Tin = np.dot(A, T_inv)
print("A = A * T_inv:")
print(A_Tin)

# Compute A_xi = T * A * T_inv
A_xi = np.dot(T, np.dot(A, T_inv))

# Compute B_xi = T * B
B_xi = np.dot(T, B)

# Display all the matrices
print("\nOriginal Matrix A:")
print(A)

print("\nOriginal Matrix B:")
print(B)

print("\nTransformation Matrix T:")
print(T)

print("\nInverse of Transformation Matrix T_inv:")
print(T_inv)

print("\nTransformed Matrix A_xi (A in the new state coordinates):")
print(A_xi)

print("\nTransformed Matrix C_xi (C in the new state coordinates):")
print(B_xi)



A = A * T_inv:
[[ -2.   1.   1.]
 [-10.  -1.  -5.]
 [ 10.  -1.   2.]]

Original Matrix A:
[[ 18   9  13]
 [ 50  23  35]
 [-65 -31 -46]]

Original Matrix B:
[ 5 -5  5]

Transformation Matrix T:
[[-4 -2 -3]
 [15  7 10]
 [-5 -2 -3]]

Inverse of Transformation Matrix T_inv:
[[ 1.00000000e+00 -4.73695157e-16 -1.00000000e+00]
 [ 5.00000000e+00  3.00000000e+00  5.00000000e+00]
 [-5.00000000e+00 -2.00000000e+00 -2.00000000e+00]]

Transformed Matrix A_xi (A in the new state coordinates):
[[-2.00000000e+00  1.00000000e+00  1.11022302e-14]
 [ 6.03961325e-14 -2.00000000e+00 -3.64153152e-14]
 [-1.59872116e-14  7.10542736e-15 -1.00000000e+00]]

Transformed Matrix C_xi (C in the new state coordinates):
[-25  90 -30]
